namespace Wacton.Desu.Enums
{
    using System.Collections.Generic;

    using Wacton.Desu.Kanji;
    using Wacton.Tovarisch.Enum;

    public class ClassicalBushuRadical : Enumeration, IBushuRadical
    {
        public static readonly ClassicalBushuRadical Radical001 = new ClassicalBushuRadical("Radical001", 1, "一");
        public static readonly ClassicalBushuRadical Radical002 = new ClassicalBushuRadical("Radical002", 2, "丨");
        public static readonly ClassicalBushuRadical Radical003 = new ClassicalBushuRadical("Radical003", 3, "丶");
        public static readonly ClassicalBushuRadical Radical004 = new ClassicalBushuRadical("Radical004", 4, "丿");
        public static readonly ClassicalBushuRadical Radical005 = new ClassicalBushuRadical("Radical005", 5, "乙 ", new List<string> { "乚" });
        public static readonly ClassicalBushuRadical Radical006 = new ClassicalBushuRadical("Radical006", 6, "亅");
        public static readonly ClassicalBushuRadical Radical007 = new ClassicalBushuRadical("Radical007", 7, "二");
        public static readonly ClassicalBushuRadical Radical008 = new ClassicalBushuRadical("Radical008", 8, "亠");
        public static readonly ClassicalBushuRadical Radical009 = new ClassicalBushuRadical("Radical009", 9, "人 ", new List<string> { "亻", "𠆢" });
        public static readonly ClassicalBushuRadical Radical010 = new ClassicalBushuRadical("Radical010", 10, "儿");
        public static readonly ClassicalBushuRadical Radical011 = new ClassicalBushuRadical("Radical011", 11, "入 ", new List<string> { "𠆢" });
        public static readonly ClassicalBushuRadical Radical012 = new ClassicalBushuRadical("Radical012", 12, "八 ", new List<string> { "ハ" });
        public static readonly ClassicalBushuRadical Radical013 = new ClassicalBushuRadical("Radical013", 13, "冂");
        public static readonly ClassicalBushuRadical Radical014 = new ClassicalBushuRadical("Radical014", 14, "冖");
        public static readonly ClassicalBushuRadical Radical015 = new ClassicalBushuRadical("Radical015", 15, "冫");
        public static readonly ClassicalBushuRadical Radical016 = new ClassicalBushuRadical("Radical016", 16, "几");
        public static readonly ClassicalBushuRadical Radical017 = new ClassicalBushuRadical("Radical017", 17, "凵");
        public static readonly ClassicalBushuRadical Radical018 = new ClassicalBushuRadical("Radical018", 18, "刀 ", new List<string> { "刂", "⺈" });
        public static readonly ClassicalBushuRadical Radical019 = new ClassicalBushuRadical("Radical019", 19, "力");
        public static readonly ClassicalBushuRadical Radical020 = new ClassicalBushuRadical("Radical020", 20, "勹");
        public static readonly ClassicalBushuRadical Radical021 = new ClassicalBushuRadical("Radical021", 21, "匕");
        public static readonly ClassicalBushuRadical Radical022 = new ClassicalBushuRadical("Radical022", 22, "匚");
        public static readonly ClassicalBushuRadical Radical023 = new ClassicalBushuRadical("Radical023", 23, "亡 ", new List<string> { "匸" });
        public static readonly ClassicalBushuRadical Radical024 = new ClassicalBushuRadical("Radical024", 24, "十");
        public static readonly ClassicalBushuRadical Radical025 = new ClassicalBushuRadical("Radical025", 25, "卜 ", new List<string> { "⼘", "⺊" });
        public static readonly ClassicalBushuRadical Radical026 = new ClassicalBushuRadical("Radical026", 26, "卩 ", new List<string> { "㔾" });
        public static readonly ClassicalBushuRadical Radical027 = new ClassicalBushuRadical("Radical027", 27, "厂");
        public static readonly ClassicalBushuRadical Radical028 = new ClassicalBushuRadical("Radical028", 28, "厶");
        public static readonly ClassicalBushuRadical Radical029 = new ClassicalBushuRadical("Radical029", 29, "又");
        public static readonly ClassicalBushuRadical Radical030 = new ClassicalBushuRadical("Radical030", 30, "口");
        public static readonly ClassicalBushuRadical Radical031 = new ClassicalBushuRadical("Radical031", 31, "囗");
        public static readonly ClassicalBushuRadical Radical032 = new ClassicalBushuRadical("Radical032", 32, "土");
        public static readonly ClassicalBushuRadical Radical033 = new ClassicalBushuRadical("Radical033", 33, "士");
        public static readonly ClassicalBushuRadical Radical034 = new ClassicalBushuRadical("Radical034", 34, "夂");
        public static readonly ClassicalBushuRadical Radical035 = new ClassicalBushuRadical("Radical035", 35, "夊");
        public static readonly ClassicalBushuRadical Radical036 = new ClassicalBushuRadical("Radical036", 36, "夕");
        public static readonly ClassicalBushuRadical Radical037 = new ClassicalBushuRadical("Radical037", 37, "大");
        public static readonly ClassicalBushuRadical Radical038 = new ClassicalBushuRadical("Radical038", 38, "女");
        public static readonly ClassicalBushuRadical Radical039 = new ClassicalBushuRadical("Radical039", 39, "子");
        public static readonly ClassicalBushuRadical Radical040 = new ClassicalBushuRadical("Radical040", 40, "宀");
        public static readonly ClassicalBushuRadical Radical041 = new ClassicalBushuRadical("Radical041", 41, "寸");
        public static readonly ClassicalBushuRadical Radical042 = new ClassicalBushuRadical("Radical042", 42, "小 ", new List<string> { "⺌", " ⺍" });
        public static readonly ClassicalBushuRadical Radical043 = new ClassicalBushuRadical("Radical043", 43, "尢 ", new List<string> { "尤", "尣" });
        public static readonly ClassicalBushuRadical Radical044 = new ClassicalBushuRadical("Radical044", 44, "尸");
        public static readonly ClassicalBushuRadical Radical045 = new ClassicalBushuRadical("Radical045", 45, "屮");
        public static readonly ClassicalBushuRadical Radical046 = new ClassicalBushuRadical("Radical046", 46, "山");
        public static readonly ClassicalBushuRadical Radical047 = new ClassicalBushuRadical("Radical047", 47, "巛 ", new List<string> { "川", "巜" });
        public static readonly ClassicalBushuRadical Radical048 = new ClassicalBushuRadical("Radical048", 48, "工");
        public static readonly ClassicalBushuRadical Radical049 = new ClassicalBushuRadical("Radical049", 49, "已 ", new List<string> { "己", "巳" });
        public static readonly ClassicalBushuRadical Radical050 = new ClassicalBushuRadical("Radical050", 50, "巾");
        public static readonly ClassicalBushuRadical Radical051 = new ClassicalBushuRadical("Radical051", 51, "干");
        public static readonly ClassicalBushuRadical Radical052 = new ClassicalBushuRadical("Radical052", 52, "幺");
        public static readonly ClassicalBushuRadical Radical053 = new ClassicalBushuRadical("Radical053", 53, "广");
        public static readonly ClassicalBushuRadical Radical054 = new ClassicalBushuRadical("Radical054", 54, "廴");
        public static readonly ClassicalBushuRadical Radical055 = new ClassicalBushuRadical("Radical055", 55, "廾");
        public static readonly ClassicalBushuRadical Radical056 = new ClassicalBushuRadical("Radical056", 56, "弋");
        public static readonly ClassicalBushuRadical Radical057 = new ClassicalBushuRadical("Radical057", 57, "弓");
        public static readonly ClassicalBushuRadical Radical058 = new ClassicalBushuRadical("Radical058", 58, "彐 ", new List<string> { "彑" });
        public static readonly ClassicalBushuRadical Radical059 = new ClassicalBushuRadical("Radical059", 59, "彡");
        public static readonly ClassicalBushuRadical Radical060 = new ClassicalBushuRadical("Radical060", 60, "彳");
        public static readonly ClassicalBushuRadical Radical061 = new ClassicalBushuRadical("Radical061", 61, "心 ", new List<string> { "忄", "⺗" });
        public static readonly ClassicalBushuRadical Radical062 = new ClassicalBushuRadical("Radical062", 62, "戈");
        public static readonly ClassicalBushuRadical Radical063 = new ClassicalBushuRadical("Radical063", 63, "戸 ", new List<string> { "戶", "户" });
        public static readonly ClassicalBushuRadical Radical064 = new ClassicalBushuRadical("Radical064", 64, "手 ", new List<string> { "扌", "龵" });
        public static readonly ClassicalBushuRadical Radical065 = new ClassicalBushuRadical("Radical065", 65, "支");
        public static readonly ClassicalBushuRadical Radical066 = new ClassicalBushuRadical("Radical066", 66, "攵 ", new List<string> { "攴" });
        public static readonly ClassicalBushuRadical Radical067 = new ClassicalBushuRadical("Radical067", 67, "文");
        public static readonly ClassicalBushuRadical Radical068 = new ClassicalBushuRadical("Radical068", 68, "斗");
        public static readonly ClassicalBushuRadical Radical069 = new ClassicalBushuRadical("Radical069", 69, "斤");
        public static readonly ClassicalBushuRadical Radical070 = new ClassicalBushuRadical("Radical070", 70, "方");
        public static readonly ClassicalBushuRadical Radical071 = new ClassicalBushuRadical("Radical071", 71, "无 ", new List<string> { "旡" });
        public static readonly ClassicalBushuRadical Radical072 = new ClassicalBushuRadical("Radical072", 72, "日");
        public static readonly ClassicalBushuRadical Radical073 = new ClassicalBushuRadical("Radical073", 73, "曰");
        public static readonly ClassicalBushuRadical Radical074 = new ClassicalBushuRadical("Radical074", 74, "月 ", new List<string> { "⺝" });
        public static readonly ClassicalBushuRadical Radical075 = new ClassicalBushuRadical("Radical075", 75, "木");
        public static readonly ClassicalBushuRadical Radical076 = new ClassicalBushuRadical("Radical076", 76, "欠");
        public static readonly ClassicalBushuRadical Radical077 = new ClassicalBushuRadical("Radical077", 77, "止");
        public static readonly ClassicalBushuRadical Radical078 = new ClassicalBushuRadical("Radical078", 78, "歹 ", new List<string> { "歺" });
        public static readonly ClassicalBushuRadical Radical079 = new ClassicalBushuRadical("Radical079", 79, "殳");
        public static readonly ClassicalBushuRadical Radical080 = new ClassicalBushuRadical("Radical080", 80, "毋 ", new List<string> { "母", "⺟" });
        public static readonly ClassicalBushuRadical Radical081 = new ClassicalBushuRadical("Radical081", 81, "比");
        public static readonly ClassicalBushuRadical Radical082 = new ClassicalBushuRadical("Radical082", 82, "毛");
        public static readonly ClassicalBushuRadical Radical083 = new ClassicalBushuRadical("Radical083", 83, "氏");
        public static readonly ClassicalBushuRadical Radical084 = new ClassicalBushuRadical("Radical084", 84, "气");
        public static readonly ClassicalBushuRadical Radical085 = new ClassicalBushuRadical("Radical085", 85, "水 ", new List<string> { "氵", "氺" });
        public static readonly ClassicalBushuRadical Radical086 = new ClassicalBushuRadical("Radical086", 86, "火 ", new List<string> { "灬" });
        public static readonly ClassicalBushuRadical Radical087 = new ClassicalBushuRadical("Radical087", 87, "爪 ", new List<string> { "爫", "⺥", "⺤" });
        public static readonly ClassicalBushuRadical Radical088 = new ClassicalBushuRadical("Radical088", 88, "父");
        public static readonly ClassicalBushuRadical Radical089 = new ClassicalBushuRadical("Radical089", 89, "爻");
        public static readonly ClassicalBushuRadical Radical090 = new ClassicalBushuRadical("Radical090", 90, "爿 ", new List<string> { "丬" });
        public static readonly ClassicalBushuRadical Radical091 = new ClassicalBushuRadical("Radical091", 91, "片");
        public static readonly ClassicalBushuRadical Radical092 = new ClassicalBushuRadical("Radical092", 92, "牙");
        public static readonly ClassicalBushuRadical Radical093 = new ClassicalBushuRadical("Radical093", 93, "牛 ", new List<string> { "牜", " ⺧" });
        public static readonly ClassicalBushuRadical Radical094 = new ClassicalBushuRadical("Radical094", 94, "犬 ", new List<string> { "犭" });
        public static readonly ClassicalBushuRadical Radical095 = new ClassicalBushuRadical("Radical095", 95, "玄");
        public static readonly ClassicalBushuRadical Radical096 = new ClassicalBushuRadical("Radical096", 96, "王 ", new List<string> { "玉", " 玊", " ⺩" });
        public static readonly ClassicalBushuRadical Radical097 = new ClassicalBushuRadical("Radical097", 97, "瓜");
        public static readonly ClassicalBushuRadical Radical098 = new ClassicalBushuRadical("Radical098", 98, "瓦");
        public static readonly ClassicalBushuRadical Radical099 = new ClassicalBushuRadical("Radical099", 99, "甘");
        public static readonly ClassicalBushuRadical Radical100 = new ClassicalBushuRadical("Radical100", 100, "生");
        public static readonly ClassicalBushuRadical Radical101 = new ClassicalBushuRadical("Radical101", 101, "用 ", new List<string> { "甩" });
        public static readonly ClassicalBushuRadical Radical102 = new ClassicalBushuRadical("Radical102", 102, "田");
        public static readonly ClassicalBushuRadical Radical103 = new ClassicalBushuRadical("Radical103", 103, "疋 ", new List<string> { "⺪" });
        public static readonly ClassicalBushuRadical Radical104 = new ClassicalBushuRadical("Radical104", 104, "疒");
        public static readonly ClassicalBushuRadical Radical105 = new ClassicalBushuRadical("Radical105", 105, "癶");
        public static readonly ClassicalBushuRadical Radical106 = new ClassicalBushuRadical("Radical106", 106, "白");
        public static readonly ClassicalBushuRadical Radical107 = new ClassicalBushuRadical("Radical107", 107, "皮");
        public static readonly ClassicalBushuRadical Radical108 = new ClassicalBushuRadical("Radical108", 108, "皿");
        public static readonly ClassicalBushuRadical Radical109 = new ClassicalBushuRadical("Radical109", 109, "目");
        public static readonly ClassicalBushuRadical Radical110 = new ClassicalBushuRadical("Radical110", 110, "矛");
        public static readonly ClassicalBushuRadical Radical111 = new ClassicalBushuRadical("Radical111", 111, "矢");
        public static readonly ClassicalBushuRadical Radical112 = new ClassicalBushuRadical("Radical112", 112, "石");
        public static readonly ClassicalBushuRadical Radical113 = new ClassicalBushuRadical("Radical113", 113, "示 ", new List<string> { "礻" });
        public static readonly ClassicalBushuRadical Radical114 = new ClassicalBushuRadical("Radical114", 114, "禸");
        public static readonly ClassicalBushuRadical Radical115 = new ClassicalBushuRadical("Radical115", 115, "禾");
        public static readonly ClassicalBushuRadical Radical116 = new ClassicalBushuRadical("Radical116", 116, "穴");
        public static readonly ClassicalBushuRadical Radical117 = new ClassicalBushuRadical("Radical117", 117, "立");
        public static readonly ClassicalBushuRadical Radical118 = new ClassicalBushuRadical("Radical118", 118, "竹 ", new List<string> { "⺮" });
        public static readonly ClassicalBushuRadical Radical119 = new ClassicalBushuRadical("Radical119", 119, "米");
        public static readonly ClassicalBushuRadical Radical120 = new ClassicalBushuRadical("Radical120", 120, "糸 ", new List<string> { "糹" });
        public static readonly ClassicalBushuRadical Radical121 = new ClassicalBushuRadical("Radical121", 121, "缶");
        public static readonly ClassicalBushuRadical Radical122 = new ClassicalBushuRadical("Radical122", 122, "罒 ", new List<string> { "网", "罓", "⺲", "⺳" });
        public static readonly ClassicalBushuRadical Radical123 = new ClassicalBushuRadical("Radical123", 123, "羊 ", new List<string> { "⺶", "⺷" });
        public static readonly ClassicalBushuRadical Radical124 = new ClassicalBushuRadical("Radical124", 124, "羽");
        public static readonly ClassicalBushuRadical Radical125 = new ClassicalBushuRadical("Radical125", 125, "耂 ", new List<string> { "老", "⺹" });
        public static readonly ClassicalBushuRadical Radical126 = new ClassicalBushuRadical("Radical126", 126, "而");
        public static readonly ClassicalBushuRadical Radical127 = new ClassicalBushuRadical("Radical127", 127, "耒");
        public static readonly ClassicalBushuRadical Radical128 = new ClassicalBushuRadical("Radical128", 128, "耳");
        public static readonly ClassicalBushuRadical Radical129 = new ClassicalBushuRadical("Radical129", 129, "聿 ", new List<string> { "⺻" });
        public static readonly ClassicalBushuRadical Radical130 = new ClassicalBushuRadical("Radical130", 130, "肉 ", new List<string> { "⺼", "月" });
        public static readonly ClassicalBushuRadical Radical131 = new ClassicalBushuRadical("Radical131", 131, "臣");
        public static readonly ClassicalBushuRadical Radical132 = new ClassicalBushuRadical("Radical132", 132, "自");
        public static readonly ClassicalBushuRadical Radical133 = new ClassicalBushuRadical("Radical133", 133, "至");
        public static readonly ClassicalBushuRadical Radical134 = new ClassicalBushuRadical("Radical134", 134, "臼");
        public static readonly ClassicalBushuRadical Radical135 = new ClassicalBushuRadical("Radical135", 135, "舌");
        public static readonly ClassicalBushuRadical Radical136 = new ClassicalBushuRadical("Radical136", 136, "舛");
        public static readonly ClassicalBushuRadical Radical137 = new ClassicalBushuRadical("Radical137", 137, "舟");
        public static readonly ClassicalBushuRadical Radical138 = new ClassicalBushuRadical("Radical138", 138, "艮");
        public static readonly ClassicalBushuRadical Radical139 = new ClassicalBushuRadical("Radical139", 139, "色");
        public static readonly ClassicalBushuRadical Radical140 = new ClassicalBushuRadical("Radical140", 140, "艹 ", new List<string> { "艸", "䒑" });
        public static readonly ClassicalBushuRadical Radical141 = new ClassicalBushuRadical("Radical141", 141, "虍");
        public static readonly ClassicalBushuRadical Radical142 = new ClassicalBushuRadical("Radical142", 142, "虫");
        public static readonly ClassicalBushuRadical Radical143 = new ClassicalBushuRadical("Radical143", 143, "血");
        public static readonly ClassicalBushuRadical Radical144 = new ClassicalBushuRadical("Radical144", 144, "行");
        public static readonly ClassicalBushuRadical Radical145 = new ClassicalBushuRadical("Radical145", 145, "衣 ", new List<string> { "衤" });
        public static readonly ClassicalBushuRadical Radical146 = new ClassicalBushuRadical("Radical146", 146, "西 ", new List<string> { "襾", "覀" });
        public static readonly ClassicalBushuRadical Radical147 = new ClassicalBushuRadical("Radical147", 147, "見");
        public static readonly ClassicalBushuRadical Radical148 = new ClassicalBushuRadical("Radical148", 148, "角");
        public static readonly ClassicalBushuRadical Radical149 = new ClassicalBushuRadical("Radical149", 149, "言 ", new List<string> { "訁" });
        public static readonly ClassicalBushuRadical Radical150 = new ClassicalBushuRadical("Radical150", 150, "谷");
        public static readonly ClassicalBushuRadical Radical151 = new ClassicalBushuRadical("Radical151", 151, "豆");
        public static readonly ClassicalBushuRadical Radical152 = new ClassicalBushuRadical("Radical152", 152, "豕");
        public static readonly ClassicalBushuRadical Radical153 = new ClassicalBushuRadical("Radical153", 153, "豸");
        public static readonly ClassicalBushuRadical Radical154 = new ClassicalBushuRadical("Radical154", 154, "貝");
        public static readonly ClassicalBushuRadical Radical155 = new ClassicalBushuRadical("Radical155", 155, "赤");
        public static readonly ClassicalBushuRadical Radical156 = new ClassicalBushuRadical("Radical156", 156, "走 ", new List<string> { "赱" });
        public static readonly ClassicalBushuRadical Radical157 = new ClassicalBushuRadical("Radical157", 157, "足 ", new List<string> { "⻊" });
        public static readonly ClassicalBushuRadical Radical158 = new ClassicalBushuRadical("Radical158", 158, "身");
        public static readonly ClassicalBushuRadical Radical159 = new ClassicalBushuRadical("Radical159", 159, "車");
        public static readonly ClassicalBushuRadical Radical160 = new ClassicalBushuRadical("Radical160", 160, "辛");
        public static readonly ClassicalBushuRadical Radical161 = new ClassicalBushuRadical("Radical161", 161, "辰");
        public static readonly ClassicalBushuRadical Radical162 = new ClassicalBushuRadical("Radical162", 162, "⻌ ", new List<string> { "辵", "辶" });
        public static readonly ClassicalBushuRadical Radical163 = new ClassicalBushuRadical("Radical163", 163, "阝 ", new List<string> { "邑", "⻏" });
        public static readonly ClassicalBushuRadical Radical164 = new ClassicalBushuRadical("Radical164", 164, "酉");
        public static readonly ClassicalBushuRadical Radical165 = new ClassicalBushuRadical("Radical165", 165, "釆");
        public static readonly ClassicalBushuRadical Radical166 = new ClassicalBushuRadical("Radical166", 166, "里");
        public static readonly ClassicalBushuRadical Radical167 = new ClassicalBushuRadical("Radical167", 167, "金 ", new List<string> { "釒" });
        public static readonly ClassicalBushuRadical Radical168 = new ClassicalBushuRadical("Radical168", 168, "長 ", new List<string> { "镸" });
        public static readonly ClassicalBushuRadical Radical169 = new ClassicalBushuRadical("Radical169", 169, "門");
        public static readonly ClassicalBushuRadical Radical170 = new ClassicalBushuRadical("Radical170", 170, "阝 ", new List<string> { "阜", "⻖" });
        public static readonly ClassicalBushuRadical Radical171 = new ClassicalBushuRadical("Radical171", 171, "隶");
        public static readonly ClassicalBushuRadical Radical172 = new ClassicalBushuRadical("Radical172", 172, "隹");
        public static readonly ClassicalBushuRadical Radical173 = new ClassicalBushuRadical("Radical173", 173, "雨 ", new List<string> { "⻗" });
        public static readonly ClassicalBushuRadical Radical174 = new ClassicalBushuRadical("Radical174", 174, "青 ", new List<string> { "靑" });
        public static readonly ClassicalBushuRadical Radical175 = new ClassicalBushuRadical("Radical175", 175, "非");
        public static readonly ClassicalBushuRadical Radical176 = new ClassicalBushuRadical("Radical176", 176, "面 ", new List<string> { "靣" });
        public static readonly ClassicalBushuRadical Radical177 = new ClassicalBushuRadical("Radical177", 177, "革");
        public static readonly ClassicalBushuRadical Radical178 = new ClassicalBushuRadical("Radical178", 178, "韋");
        public static readonly ClassicalBushuRadical Radical179 = new ClassicalBushuRadical("Radical179", 179, "韭");
        public static readonly ClassicalBushuRadical Radical180 = new ClassicalBushuRadical("Radical180", 180, "音");
        public static readonly ClassicalBushuRadical Radical181 = new ClassicalBushuRadical("Radical181", 181, "頁");
        public static readonly ClassicalBushuRadical Radical182 = new ClassicalBushuRadical("Radical182", 182, "風 ", new List<string> { "𠘨" });
        public static readonly ClassicalBushuRadical Radical183 = new ClassicalBushuRadical("Radical183", 183, "飛");
        public static readonly ClassicalBushuRadical Radical184 = new ClassicalBushuRadical("Radical184", 184, "食 ", new List<string> { "飠" });
        public static readonly ClassicalBushuRadical Radical185 = new ClassicalBushuRadical("Radical185", 185, "首");
        public static readonly ClassicalBushuRadical Radical186 = new ClassicalBushuRadical("Radical186", 186, "香");
        public static readonly ClassicalBushuRadical Radical187 = new ClassicalBushuRadical("Radical187", 187, "馬");
        public static readonly ClassicalBushuRadical Radical188 = new ClassicalBushuRadical("Radical188", 188, "骨");
        public static readonly ClassicalBushuRadical Radical189 = new ClassicalBushuRadical("Radical189", 189, "高 ", new List<string> { "髙" });
        public static readonly ClassicalBushuRadical Radical190 = new ClassicalBushuRadical("Radical190", 190, "髟");
        public static readonly ClassicalBushuRadical Radical191 = new ClassicalBushuRadical("Radical191", 191, "鬥");
        public static readonly ClassicalBushuRadical Radical192 = new ClassicalBushuRadical("Radical192", 192, "鬯");
        public static readonly ClassicalBushuRadical Radical193 = new ClassicalBushuRadical("Radical193", 193, "鬲");
        public static readonly ClassicalBushuRadical Radical194 = new ClassicalBushuRadical("Radical194", 194, "鬼");
        public static readonly ClassicalBushuRadical Radical195 = new ClassicalBushuRadical("Radical195", 195, "魚");
        public static readonly ClassicalBushuRadical Radical196 = new ClassicalBushuRadical("Radical196", 196, "鳥");
        public static readonly ClassicalBushuRadical Radical197 = new ClassicalBushuRadical("Radical197", 197, "鹵");
        public static readonly ClassicalBushuRadical Radical198 = new ClassicalBushuRadical("Radical198", 198, "鹿");
        public static readonly ClassicalBushuRadical Radical199 = new ClassicalBushuRadical("Radical199", 199, "麦 ", new List<string> { "麥" });
        public static readonly ClassicalBushuRadical Radical200 = new ClassicalBushuRadical("Radical200", 200, "麻");
        public static readonly ClassicalBushuRadical Radical201 = new ClassicalBushuRadical("Radical201", 201, "黄 ", new List<string> { "黃" });
        public static readonly ClassicalBushuRadical Radical202 = new ClassicalBushuRadical("Radical202", 202, "黍");
        public static readonly ClassicalBushuRadical Radical203 = new ClassicalBushuRadical("Radical203", 203, "黒 ", new List<string> { "黑" });
        public static readonly ClassicalBushuRadical Radical204 = new ClassicalBushuRadical("Radical204", 204, "黹");
        public static readonly ClassicalBushuRadical Radical205 = new ClassicalBushuRadical("Radical205", 205, "黽");
        public static readonly ClassicalBushuRadical Radical206 = new ClassicalBushuRadical("Radical206", 206, "鼎");
        public static readonly ClassicalBushuRadical Radical207 = new ClassicalBushuRadical("Radical207", 207, "鼓");
        public static readonly ClassicalBushuRadical Radical208 = new ClassicalBushuRadical("Radical208", 208, "鼠");
        public static readonly ClassicalBushuRadical Radical209 = new ClassicalBushuRadical("Radical209", 209, "鼻");
        public static readonly ClassicalBushuRadical Radical210 = new ClassicalBushuRadical("Radical210", 210, "齊");
        public static readonly ClassicalBushuRadical Radical211 = new ClassicalBushuRadical("Radical211", 211, "歯 ", new List<string> { "齒" });
        public static readonly ClassicalBushuRadical Radical212 = new ClassicalBushuRadical("Radical212", 212, "竜 ", new List<string> { "龍" });
        public static readonly ClassicalBushuRadical Radical213 = new ClassicalBushuRadical("Radical213", 213, "亀 ", new List<string> { "龜" });
        public static readonly ClassicalBushuRadical Radical214 = new ClassicalBushuRadical("Radical214", 214, "龠");

        public BushuRadicalType Type => BushuRadicalType.Classical;
        public int Number { get; }
        public string Radical { get; }
        public IEnumerable<string> Variants { get; } 

        public ClassicalBushuRadical(string displayName, int number, string radical, IEnumerable<string> variants = null)
            : base(displayName)
        {
            this.Radical = radical;
            this.Number = number;
            this.Variants = variants ?? new List<string>();
        }

        public override string ToString()
        {
            return $"{this.Type} #{this.Number.ToString().PadLeft(3, '0')} ({this.Radical})";
        }
    }
}